/*    ==Parâmetros de Script==

    Versão do Servidor de Origem : SQL Server 2017 (14.0.2002)
    Edição do Mecanismo de Banco de Dados de Origem : Microsoft SQL Server Express Edition
    Tipo do Mecanismo de Banco de Dados de Origem : SQL Server Autônomo

    Versão do Servidor de Destino : SQL Server 2017
    Edição de Mecanismo de Banco de Dados de Destino : Microsoft SQL Server Express Edition
    Tipo de Mecanismo de Banco de Dados de Destino : SQL Server Autônomo
*/

USE [master]
GO

/****** Object:  Database [ProjetoEstagioSupDDD]    Script Date: 13/12/2018 17:48:56 ******/
CREATE DATABASE [ProjetoEstagioSupDDD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjetoEstagioSupDDD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ProjetoEstagioSupDDD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjetoEstagioSupDDD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ProjetoEstagioSupDDD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjetoEstagioSupDDD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET  MULTI_USER 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET QUERY_STORE = OFF
GO

USE [ProjetoEstagioSupDDD]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ProjetoEstagioSupDDD] SET  READ_WRITE 
GO


